services:
  cli-proxy-api:
    image: local/cpa:v1.0.1
    pull_policy: always
    container_name: cli-proxy-api
    # env_file:
    #   - .env
    environment:
      DEPLOY: ${DEPLOY:-}
    ports:
      - "8317:8317"
    volumes:
      - /data/docker/cpa/config.yaml:/CLIProxyAPI/config.yaml
      - /data/docker/cpa/auths:/root/.cli-proxy-api
      - /data/docker/cpa/logs:/CLIProxyAPI/logs
    restart: unless-stopped
